version: '3.8'
services:
  db:
    image: mysql:8.1.0
    container_name: MySQL-SaleWeb
    restart: always
    environment:
      - MYSQL_DATABASE=SaleWeb
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
    name: SaleWebDB